server:
  port: 8080


school.private.key: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBALljngboWWZN1Yr8
  hEo9BL82E6eqGUkzgC1WAenLtVieGaEZAZzvHGmYMyc15D8E35aTCHaC2YVMD95V
  CP+3fyaZ/LmZ22PcX8wupIF2ixmgeYt6R2HREDdFDY3IzMK0CpOT4Mgwy1TwFHQx
  WSrtzLRQgHM7Ji+NEvjH4duYwrTnAgMBAAECgYB63Ks5Nrkw1LqF/u4JaUEBG+yQ
  vGk/mxMCeLKR6EBJ95VSr4jjIZB55rVX8h5PKYKofs8oA3X3Ij6OAVsSZeCsarKU
  ioQClEb8vh8VetKiTnwtHqdjB1FjkOUjCJnmUVlBaEJAalwnBBRmLwKVUqoh2UoZ
  UXukHzxcef3bzhUGgQJBANvA/jG8E4rzSMQ6EXLZHJnRwQXWo5HhIvUjwEaywysG
  TXHf9aze845Srad5GyTpnOryoYympaIl0PknPKJtocECQQDX95arAvljwFVvVR7t
  6m+N4zxLkUZWl8uVLtRUSvALQYuA9zR76nBjEB/uuavTGVOCLRxDOaR7uAiJfRTb
  ajCnAkAiE+yXY9YX/yAypdqc18RSqi9nq2BUN/iG0VN44zHW0zRhS1y6wRw93t5l
  ESe/cqbN3HBm8lTPL1QXvxjtC1lBAkEAqzMpzQbei6S8FTV0/0UIiYHJGl5fU+Wh
  DPHCf8+n2kRrQiC1CkYeMWlm5udovj8lY9w+u0vGiAyrN9Jf5k+XoQJAbOBm1rai
  k/kDe/JCzNe4HQVfAjCsFWQnBLJAAbrTaRYyq/PZQtqX8+6G/tlsZP7FsB5iC0lA
  5387yO5KNCfDdA==

school.public.key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC5Y54G6FlmTdWK/IRKPQS/NhOn
  qhlJM4AtVgHpy7VYnhmhGQGc7xxpmDMnNeQ/BN+Wkwh2gtmFTA/eVQj/t38mmfy5
  mdtj3F/MLqSBdosZoHmLekdh0RA3RQ2NyMzCtAqTk+DIMMtU8BR0MVkq7cy0UIBz
  OyYvjRL4x+HbmMK05wIDAQAB